version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: msvc_courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-users:
    container_name: msvc-users
    image: alexispetro/users:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-users/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./msvc-users/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  msvc-courses:
    container_name: msvc-courses
    image: alexispetro/courses:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-courses/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-courses/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-users
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:

#docker-compose help
#docker-compose up --build -d (forzar creacion de imagenes en caso de cambio)


